# Welcome to Jekyll!
# This is the default format. 
# For more see: http://jekyllrb.com/docs/permalinks/

# Themes are encouraged to use these universal variables 
# so be sure to set them if your theme uses them.
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Hung-Chi's Blog
brief-intro: on github
url: "http://hungchicheng.me" # the base hostname & protocol for your site
description: > # this means to ignore newlines until "baseurl:"
  Hung-Chi's Blog 程弘錡的部落格, hungchi cheng, 
  內容包含身為軟體工程師的作者所遇到的各種技術問題與解決方法,
  主要講述 Cocos2d-x Lua 還有架部落格 等等相關的內容.
  Blog includes a variety of technical problems and solutions encountered by myself. 
  Mainly content is writing about Cocos2d-x + Lua and so on the relevant content.

baseurl: "" # the subpath of your site, e.g. /blog

# The url is only used when full-domain names are needed
# such as sitemap.txt 
# Most places will/should use BASE_PATH to make the urls
#
# If you have set a CNAME (pages.github.com) set your custom domain here.
# Else if you are pushing to username.github.io, replace with your username.
# Finally if you are pushing to a GitHub project page, include the project name at the end.
#


permalink: /:year/:month/:day/:title/

# other links
twitter_username: hungchicheng
# facebook_username: hungchicheng
github_username:  hungchicheng
email: hungchi117@gmail.com
# weibo_username: hungchicheng
# zhihu_username: hungchicheng
linkedIn_username: hungchicheng
# dribbble_username: hungchicheng


# comments
# two ways to comment, only choose one, and use your own short name
# 两种评论插件，选一个就好了，使用自己的 short_name
duoshuo_shortname: #hungchichenggithubio
disqus_shortname: hungchichenggithubio

# statistic analysis 统计代码
# 百度统计 id，将统计代码替换为自己的百度统计id，即
# hm.src = "//hm.baidu.com/hm.js?xxxxxxxxxxxx";
# xxxxx字符串
baidu_tongji_id: 68fa49ae523bb9f40719bd17100dc589
google_analytics_id: UA-98981883-1 # google 分析追踪id

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

# port
# port: 1234

# These paths are to the main pages Jekyll-Bootstrap ships with.
# Some JB helpers refer to these paths; change them here if needed.
#
# archive_path: /archive.html
category_dir: category/
tag_dir: tag/
# atom_path : /atom.xml
# rss_path : /rss.xml

# gems
gems: [jekyll-paginate, jekyll-sitemap] #, jekyll-admin]

# paginate
paginate: 3
# excerpt
excerpt_separator: "<!-- more -->"

# personal def
post_end_sentence: "!!!!!!如果有任何問題,歡迎在下方提出哦!!!!!!"